parameters:

  doctrine_listener_bundle.lce_listener.class: Bug\DoctrineListenerBundle\EventListener\LifecycleEventListener
  doctrine_listener_bundle.map_service.class: Bug\DoctrineListenerBundle\Service\MapService

services:

  doctrine_listener_bundle.map_service:
    class: %doctrine_listener_bundle.map_service.class%
    arguments:
      - @ivory_google_map.geocoder

  doctrine_listener_bundle.lce_listener:
    class: %doctrine_listener_bundle.lce_listener.class%
    arguments:
      - @doctrine_listener_bundle.map_service
    tags:
      - { name: doctrine.event_listener, event: postPersist }
      - { name: doctrine.event_listener, event: postUpdate }
